### PR TITLE
Removed query string params for App Search endpoints

### LINKED ISSUE #4: Function setTags in LogClickthrough seems not working
Hi, I want to implement the functionality to get a specific tag when user clicks on a link. The LogClickthrough works without setting a tag, but when I try to set a Tag, it doen't work as expected, here's my code : 

`
        $app = $client->appSearch();
	$szClick = new Request\LogClickthrough($szEngine, $szSearch, $nIdDoc);
	$szClick->setTags(['testTag']);
	// Here's my attempt to put a tag on the logClickthrough response
	$app->logClickthrough($szClick);
`

I've tried different ways to get this work but none of my attempts were successfull

### PR DESCRIPTION
**Pull request by ezimuel**
This PR fixes #4 moving the query parameters of App Search endpoints in the body request. This is a best practices reported in the documentation of App Search [here](https://www.elastic.co/guide/en/app-search/current/api-reference.html#overview-api-references-parameters).

### CODE REVIEW

File: src/AppSearch/Request/GetTopClicksAnalytics.php [hunk 1]
```diff
@@ -42,27 +45,27 @@ public function __construct(string $engineName)
...
 		return $this;
 	}
 
 
 	/**
-	 * @param int $currentPage The page to fetch. Defaults to 1
+	 * @param int $query The page to fetch. Defaults to 1
 	 */
-	public function setCurrentPage(int $currentPage): self
+	public function setCurrentPage(int $query): self
```
Comment (technige) [inline src/AppSearch/Request/GetTopClicksAnalytics.php]: The name of the argument here has changed such that it is now inconsistent with the name of the function. Is this intentional? It seems potentially confusing.

File: src/AppSearch/Request/GetTopClicksAnalytics.php [hunk 2]
```diff
@@ -42,27 +45,27 @@ public function __construct(string $engineName)
...
 		return $this;
 	}
 
 
 	/**
-	 * @param int $pageSize The number of results per page
+	 * @param int $query The number of results per page
 	 */
-	public function setPageSize(int $pageSize): self
+	public function setPageSize(int $query): self
```
Comment (technige) [inline src/AppSearch/Request/GetTopClicksAnalytics.php]: Ditto above re inconsistencies between function and argument naming.

File: src/AppSearch/Request/GetCountAnalytics.php [hunk 3]
```diff
@@ -33,6 +35,7 @@ public function __construct(string $engineName)
 	{
 		$this->method = 'GET';
 		$engine_name = urlencode($engineName);
+		$this->headers['Content-Type'] = 'application/json';
```
Comment (technige) [inline src/AppSearch/Request/GetCountAnalytics.php:38]: Is this content type affected by the compatibility header?
https://github.com/elastic/clients-team/issues/389

File: src/AppSearch/Request/ListSynonymSets.php [hunk 4]
```diff
@@ -42,7 +45,7 @@ public function __construct(string $engineName)
 	 */
 	public function setCurrentPage(int $currentPage): self
 	{
-		$this->queryParams['page[current]'] = $currentPage;
+		$this->body['filters']['date']['to'] = $currentPage;
```
Comment (technige) [inline src/AppSearch/Request/ListSynonymSets.php]: Does this work correctly if the body is empty? Or is it guaranteed that 'filters' and 'date' will already exist when this runs?

File: src/AppSearch/Request/ListSynonymSets.php [hunk 5]
```diff
@@ -52,7 +55,7 @@ public function setCurrentPage(int $currentPage): self
 	 */
 	public function setPageSize(int $pageSize): self
 	{
-		$this->queryParams['page[size]'] = $pageSize;
+		$this->body['filters']['date']['to'] = $pageSize;
```
Comment (technige) [inline src/AppSearch/Request/ListSynonymSets.php]: Ditto above.

File: src/AppSearch/Request/GetTopClicksAnalytics.php (hunk 1 above)
Comment (ezimuel) [reply src/AppSearch/Request/GetTopClicksAnalytics.php]: It looks like a bug in the code generator, I'll have a look. Thanks!

File: src/AppSearch/Request/GetCountAnalytics.php (hunk 3 above)
Comment (ezimuel) [reply src/AppSearch/Request/GetCountAnalytics.php:38]: No, the compatibility header is only for Elasticsearch.

File: src/AppSearch/Request/ListSynonymSets.php (hunk 4 above)
Comment (ezimuel) [reply src/AppSearch/Request/ListSynonymSets.php]: If `$this->body` does not exist as array, it will be created. This is [managed by PHP](https://www.php.net/manual/en/language.types.array.php#language.types.array.syntax.modifying) itself.
Moreover, the `body` property type is not defined in the [Request](https://github.com/elastic/enterprise-search-php/blob/7.13/src/Request/Request.php#L46-L49) base class, since it can be potentially also an object.

File: src/AppSearch/Request/GetTopClicksAnalytics.php (hunk 1 above)
Comment (ezimuel) [reply src/AppSearch/Request/GetTopClicksAnalytics.php]: I fixed the code generator and update the PR with the correct code.

**Comment by ezimuel** [comment]
@technige thanks for the review. I fixed the parameter name in the code generator.
